### ISSUE TITLE
Failed to install "decontX"

### ISSUE THREAD

**Issue by GYF-pixel** [campbio/decontX#10]
Hi, I tried to install R packages through"devtools::install_github("campbio/decontX")", 
however, it reports

* installing *source* package 'decontX' ...
** using staged installation
Warning in system(paste("sh", f)) : Exit code was 127
ERROR: configuration failed for package 'decontX'
* removing 'F:/R/R-4.3.1/library/decontX'

I've updated all my files, but still don't know what's wrong, could you please help me with this issue?

**Comment by joshua-d-campbell** [comment]
Hi @GYF-pixel, sorry you are having trouble with the installation. Could you let us know what system you are using (mac, linux, windows)? You could also try installing our development branch:

```
devtools::install_github("campbio/decontX@devel")
```

**Comment by yuan-yin-truly** [comment]
@GYF-pixel It also might have to do with R version 4.3.1. You can try installing again on an R version 4.2 (I am using 4.2.1).

**Comment by yuan-yin-truly** [comment]
I am going to close the issue. Let us know if you still have any questions @GYF-pixel
