### ISSUE TITLE
RNA velocity

### ISSUE THREAD

**Issue by Sirin24** [campbio/decontX#18]
I have very basic questions.

I already generated loom files using velocyto from cellranger filtered matrix and bam files. Now if I am interested in running decontX, do I use the filtered matrix as input for decontX or the raw matrix? do I need to rerun velocyto after obtaining the corrected matrix from decontX?

**Comment by joshua-d-campbell** [comment]
Hi @Sirin24,
Generally, yes, you can run decontX on the filtered matrix from CellRanger or any other tool. You can optionally supply the raw matrix to the `background` parameter which can sometimes help with decontamination when sorting or selection was done.

We haven't tested decontX in combination with velocyto so I can't give a you a definitive answer. The only thing decontX can do is remove a proportion of counts in each gene for each cell that is likely contamination from other cell types. It does not distinguish between intronic/exonic counts. It may be worth trying but hopefully using decontX won't change the velocities too much.
