### ISSUE TITLE
how to remove contamination cells based on decontX

### ISSUE THREAD

**Issue by BenxiaHu** [campbio/decontX#20]
how to remove contamination cells (cell barcodes) based on decontX?

**Comment by joshua-d-campbell** [comment]
Hello @BenxiaHu,
There is a column `colData` of the SingleCellExperiment called "decontX_contamination" that gives the estimated levels of contamination for each cell. You can filter the cells based on this vector. Here is an example:

```
# Load libraries
library(decontX)
library(SingleCellExperiment)

# Run decontX
s <- simulateContamination(seed = 12345)
sce <- SingleCellExperiment(list(counts = s$observedCounts))
sce <- decontX(sce)

# Keep cells with less than 30% contamination
sce.filter <- sce[,sce$decontX_contamination < 0.3]
```

The threshold that you use will depend on your dataset. It is a good idea to generate the decontX plots as shown in the tutorial to get a sense of the distribution of the contamination and what threshold you want to use.
